### ISSUE TITLE
Pkcs11X509Store In .net core

### ISSUE THREAD

**Issue by ppailleaud** [Pkcs11Interop/Pkcs11Interop.X509Store#14]
Hello, 

I am trying to develop a .netCore application that communicates with my TPM chip. I would like to integrate the management of X509 certificates inside for security reasons. 
So I am using Pkcs11X509Store and Pkcs11Interop. However, Pkcs11X509Store is not available in .netCore

Is a .net core version of Pkcs11 X509 Store planned?

Thank you by adavance for you reply

System.TypeLoadException: Could not load type 'Net.Pkcs11Interop.HighLevelAPI.Pkcs11' from assembly 'Pkcs11Interop, Version=5.1.1.0, Culture=neutral, PublicKeyToken=c10e9c2d8c006d2a'.
   at Net.Pkcs11Interop.X509Store.Pkcs11X509Store.GetStoreContext(String libraryPath, IPinProvider pinProvider)
   at Net.Pkcs11Interop.X509Store.Pkcs11X509Store..ctor(String libraryPath, IPinProvider pinProvider)
   at Lectra.Mob.Pki.Client.Services.TpmService.GetCertificat() in C:\community\vault-pki\cutter\src\Lectra.Mob.Pki.Client\Services\TpmService.cs:line 88
   at Lectra.Mob.Pki.Client.Services.ProvisioningCertificateService.ProvisionCertificateAsync(String commonName) in C:\community\vault-pki\cutter\src\Lectra.Mob.Pki.Client\Services\ProvisioningCerfificateService.cs:line 97
   at Lectra.Mob.Pki.Client.PkiClient.ProvisionCertificates(String cn) in C:\community\vault-pki\cutter\src\Lectra.Mob.Pki.Client\PkiClient.cs:line 59
   at Lectra.Mob.Pki.WebApp.Controllers.CertificatesFactoryController.PostCertificateProvisioningAsync(String commonName) in C:\community\vault-pki\cutter\src\Lectra.Mob.Pki.WebApp\Controllers\CertificatesFactoryController.cs:line 40

**Comment by jariq** [comment]
Freshly released [Pkcs11Interop.X509Store 0.3.0](https://github.com/Pkcs11Interop/Pkcs11Interop.X509Store/releases/tag/v0.3.0) supports .NET Standard 2.0 so it should work .NET Core 2.0 and newer.
